config/routes.rb
Rails.application.routes.draw do

  get 'space_tags/index'
  get 'space_tags/new'
  get 'space_tags/create'
  devise_for :users
  resources :users, only: [:show]
  resources :spaces do

    resources :bookings, only: [:index, :new, :create, :show]

    resources :reviews, only: [:index, :new, :create]
  end

  resources :bookings, only: [] do
    resources :messages, only: [:index, :create]
  end

  resources :space_tags, only: [:index, :new, :create]

  get '/bookings', to: 'bookings#user'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :booking
  belongs_to :from, class_name: "User"
  belongs_to :to, class_name: "User"

  validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @booking = Booking.find(params[:booking_id])
    @messages = policy_scope(@booking.messages).order(created_at: :desc)
    @message = Message.new
    authorize @message
  end

  def create
    @message = Message.new
    @booking = Booking.find(params[:booking_id])
    @message.content = params[:message][:content]
    @message.booking = @booking
    @message.from = current_user
    if @booking.space.user == current_user
      @message.to = @booking.user
    else
      @message.to = @booking.space.user
    end
    authorize @message
    @message.save
    if @message.save
      redirect_to booking_messages_path(@booking)
    else
      render :new
    end
  end
end

app/views/messages/index.html.erb
<div class="main-container">
  <div class="container message-container">
    <h1>Messages for the booking at <%= @booking.space.name %></h1>
    <% @messages.each do |message| %>
      <% if message.from.id == current_user.id %>
        <div class="notification-from">
      <% else %>
        <div class="notification-to">
      <% end %>
        <%= cl_image_tag message.from.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <div class="notification-content">
        <p><%= message.content  %> </p>
      </div>
    </div>
    <% end %>

    <div class="message_form">
      <%= simple_form_for [@booking, @message] do |f|%>
        <%= f.input :content %>
        <%= f.submit %>
      <% end %>
    </div>
    <%= link_to "back to booking", space_booking_path(@booking.space, @booking),:class => 'btn-medium' %>
  </div>
</div>