config/routes.rb
Rails.application.routes.draw do

  get 'space_tags/index'
  get 'space_tags/new'
  get 'space_tags/create'
  devise_for :users
  resources :users, only: [:show]
  resources :spaces do

    resources :bookings, only: [:index, :new, :create, :show]

    resources :reviews, only: [:index, :new, :create]
  end

  resources :bookings, only: [] do
    resources :messages, only: [:index, :create]
  end

  resources :space_tags, only: [:index, :new, :create]

  get '/bookings', to: 'bookings#user'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/space.rb
# The Space class models pop-up spaces, identified by a name and location.
# Spaces are rented by rentees via bookings
class Space < ApplicationRecord
  validates :name, presence: true
  validates :location, presence: true, uniqueness: true
  validates :price, presence: true
  validates :description, presence: true

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :tags, through: :space_tags

  mount_uploader :photo, PhotoUploader, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  def index
    if params[:city]
      @spaces = policy_scope(Space).order(created_at: :desc).where("location ILIKE ?", "%#{params[:city]}%")
    else
      @spaces = policy_scope(Space).order(created_at: :desc)
    end
    # authorize @space
    # @spaces = Space.all
    @markers = @spaces.map do |space|
      { lng: space.longitude, lat: space.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { space: space }) }
    end
  end

  def new
    @space = Space.new
    authorize @space
  end

  def create
    @space = Space.new(space_params)
    @space.user = current_user
    authorize @space
    if @space.save
      redirect_to spaces_path
    else
      render :new
    end
  end

  def show
    authorize @space
    @reviews = Review.where(space_id: @space)
    @spacetags = SpaceTag.where(space_id: @space)
    @markers = [@space].map do |space|
      {
        lng: space.longitude,
        lat: space.latitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { space: space })
      }
    end
  end

  def edit
    authorize @space
  end

  def update
    authorize @space
    if @space.update(space_params)
      redirect_to space_path(@space)
    else
      render :edit
    end
  end

  def destroy
    authorize @space
    @space.destroy
    redirect_to spaces_path
  end

  private

  def set_space
    @space = Space.find(params[:id])
  end

  def space_params
    params.require(:space).permit(:name, :location, :price, :description, :photo)
  end
end

app/views/spaces/_infowindow.html.erb
<div class="col-xs-12 col-sm-6 col-md-4">
  <%= link_to space_path(space) do %>

  <!-- Post-->
  <div class="post-module">
    <!-- Thumbnail-->
    <div class="thumbnail" >
      <div class="date">

      </div><img src="<%= space.photo %>"/>
    </div>
    <!-- Post Content-->
    <div class="post-content">
      <div class="category">Click for more info</div>
      <h1 class="title"><%= space.name %></h1>
      <h2 class="sub_title"></h2>
      <p class="description"><%= space.description %></p>

      <% end %>
    </div>
  </div>
</div>

app/views/spaces/edit.html.erb
<div class="main-container">
  <h1>Edit Space</h1>
  <%= render "./components/space_form", space: @space %>
</div>

app/views/spaces/index.html.erb
<div class="main-container">
  <div class="container">
    <h1>All spaces</h1>

  <div class="spaces-container">
    <div class="row">
      <% @spaces.each do |space| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
        <%= link_to space_path(space) do %>

        <!-- Post-->
        <div class="post-module">
          <!-- Thumbnail-->
          <div class="thumbnail" >
            <div class="date">

            </div><img src="<%= space.photo %>"/>
          </div>
          <!-- Post Content-->
          <div class="post-content">
            <div class="category">Click for more info</div>
            <h1 class="title"><%= space.name %></h1>
            <h2 class="sub_title"></h2>
            <p class="description"><%= space.description %></p>

            <% end %>
          </div>
        </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>


</div>

app/views/spaces/new.html.erb
<div class="main-container">
  <div class="container">
    <h1>Add new space</h1>
    <%= render "./components/space_form", space: @space %>
  </div>
</div>

app/views/spaces/show.html.erb
<div class="main-container">
  <div class="container">



  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @space.photo %>);">
    <div class="card-category"></div>
    <div class="card-description">
      <h1><%= @space.name %></h1>
      <p>Location: <%= @space.location %></p>
      <p>Price: <%= @space.price %></p>
      <p>Description: <%= @space.description %></p>
      <ul class="tags-list">
        <% @spacetags.each do |spacetag| %>
          <li class="tag"><%= spacetag.tag.title %></li>
        <% end %>
      </ul>
    </div>

    </div>
    <div class="button-container">
      <%= link_to "check reviews", space_reviews_path(@space), :class => "btn-medium", :id => "inline-btn" %>
      <%= link_to "Make a booking", new_space_booking_path(@space), :class => "btn-medium", :id => "inline-btn" %>
    <% if policy(@space).edit? %>
      <%= link_to "edit space", edit_space_path(@space), :class => "btn-medium", :id => "inline-btn" %> <br>
    <% end %>
    <% if policy(@space).destroy? %>
      <%= link_to "delete space", space_path(@space), method: :delete, :class => "btn-medium", :id => "inline-btn" %>
    <% end %>
    </div>

  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>