config/routes.rb
Rails.application.routes.draw do

  get 'space_tags/index'
  get 'space_tags/new'
  get 'space_tags/create'
  devise_for :users
  resources :users, only: [:show]
  resources :spaces do

    resources :bookings, only: [:index, :new, :create, :show]

    resources :reviews, only: [:index, :new, :create]
  end

  resources :bookings, only: [] do
    resources :messages, only: [:index, :create]
  end

  resources :space_tags, only: [:index, :new, :create]

  get '/bookings', to: 'bookings#user'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible " role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer navbar-fixed-bottom" >
  <div class="footer-links text-right">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "jollypopslogo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "List your space", new_space_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Messages for each booking in dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class="navbar-wagon-link" data-toggle= "dropdown">Messages</div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

            <% if @bookings.blank? && current_user.spaces.blank? %>
              <li>You have no bookings, spaces or messages yet</li>

            <% else %>
              <% @bookings.each do |booking| %>
              <li>
                <%= link_to booking_messages_path(booking) do %>
                  <p><%= booking.space.name %> - <%= booking.space.user.email %></p>
                <% end %>
              </li>
              <% end %>
              <li>
              <% @user_bookings.each do |booking| %>
                  <%= link_to booking_messages_path(booking) do %>
                  <p><%= booking.space.name %> - <%= booking.user.email %></p>
                <% end %>
              <% end %>
              <% end %>
              </li>
        </div>
      </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>