config/routes.rb
Rails.application.routes.draw do

  get 'space_tags/index'
  get 'space_tags/new'
  get 'space_tags/create'
  devise_for :users
  resources :users, only: [:show]
  resources :spaces do

    resources :bookings, only: [:index, :new, :create, :show]

    resources :reviews, only: [:index, :new, :create]
  end

  resources :bookings, only: [] do
    resources :messages, only: [:index, :create]
  end

  resources :space_tags, only: [:index, :new, :create]

  get '/bookings', to: 'bookings#user'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @space = Space.find(params[:space_id])
    @reviews = policy_scope(Review).where(space: @space)
  end

  def new
    @review = Review.new
    @space = Space.find(params[:space_id])
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @space = Space.find(params[:space_id])
    @review.space = @space
    @review.user = current_user
    authorize @review
    if @review.save!
      redirect_to space_reviews_path(@space)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/views/reviews/index.html.erb
<div class="main-container">
  <div class="container">
    <h1>Reviews</h1>
      <div class="row">
        <% @reviews.each do |review| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="container-review">
              <%= cl_image_tag review.user.photo, class: "avatar" %>
              <p><%= review.content %></p3>
              <p>
                Written by: <%= review.user.first_name %> <%= review.user.last_name %><br><%= review.created_at %>
              </p>
            </div>
          </div>
        <% end %>
      </div>


    <%= link_to "Add a review", new_space_review_path(@space), :class => "btn-medium" %>
    <%= link_to "Back to space", space_path(@space), :class => "btn-medium" %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="main-container" id="new_review">
  <div class="container">
    <h1>Add a review</h1>
    <%= render "./components/review_form", space: @space %>
  </div>
</div>